#!/usr/bin/env python

import sys
from json import loads
from subprocess import CalledProcessError, check_output


def get_gpu_stat() -> str | None:
    try:
        return loads(check_output("nvtop -s", shell=True).decode())[0]["gpu_util"]
    except CalledProcessError:
        return "err"


if __name__ == "__main__":
    util: str | None = get_gpu_stat()
    if util == "err":
        print(-1)
        sys.exit(0)

    if util is None:
        print(-1)
        sys.exit(0)
    print(util)
