#!/usr/bin/env python

from json import loads
from subprocess import CalledProcessError, check_output


def get_gpu_stat() -> list[str | None]:
    try:
        info: dict = loads(check_output("nvtop -s", shell=True).decode())[0]
        return [
            info["gpu_util"] if info["gpu_util"] is not None else "-1",
            info["temp"] if info["temp"] is not None else "-1",
        ]
    except CalledProcessError:
        return ["err", "err"]


if __name__ == "__main__":
    util: list[str | None] = get_gpu_stat()
    print(f"{util[0]}@{util[1]}")
